#!/usr/bin/env python
import bagua as DevPkg
import re


SEPARATOR = '.'
MAX_VERSION = 10

def cmd():
    import os
    os.system('python setup.py sdist upload')
    os.system('say OK')


def get_version_list():
    version = DevPkg.__version__ if hasattr(DevPkg, '__version__') else '0.0.0'
    return version.split(SEPARATOR)


def write_version(version):
    f = open(DevPkg.__path__[0] + '/__init__.py', 'r')
    content = f.read()
    f.close()
    f = open(DevPkg.__path__[0] + '/__init__.py', 'w')
    content = re.sub(r"__version__ = ['\"]([^'\"]*)['\"]", "__version__ = \'{}\'".format(version), content) 
    f.write(content)
    f.close()
    print 'version :', version

def add_version(ver_list):
    rlist = []
    mod = 1
    for x in ver_list[::-1]:
        x = int(x)
        x += mod
        mod = x // MAX_VERSION
        x %= MAX_VERSION
        x = str(x)
        rlist.append(x)
    return rlist[::-1]

def main():
    ver_list = get_version_list()
    ver_list = add_version(ver_list)
    write_version(SEPARATOR.join(ver_list))

if __name__ == '__main__':
    main()
    cmd()

